// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: communication/grpc/schema/blockchain.proto

package grpcBlockchain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{0}
}

func (x *SuccessResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *EmptyRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type Wallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{2}
}

func (x *Wallet) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ActionDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidatorID string                      `protobuf:"bytes,1,opt,name=ValidatorID,proto3" json:"ValidatorID,omitempty"`
	FAK         string                      `protobuf:"bytes,2,opt,name=FAK,proto3" json:"FAK,omitempty"`
	Results     []*ActionDataRequest_Result `protobuf:"bytes,3,rep,name=Results,proto3" json:"Results,omitempty"`
	Action      *ActionDataRequest_Action   `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *ActionDataRequest) Reset() {
	*x = ActionDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDataRequest) ProtoMessage() {}

func (x *ActionDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDataRequest.ProtoReflect.Descriptor instead.
func (*ActionDataRequest) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{3}
}

func (x *ActionDataRequest) GetValidatorID() string {
	if x != nil {
		return x.ValidatorID
	}
	return ""
}

func (x *ActionDataRequest) GetFAK() string {
	if x != nil {
		return x.FAK
	}
	return ""
}

func (x *ActionDataRequest) GetResults() []*ActionDataRequest_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ActionDataRequest) GetAction() *ActionDataRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

// The request message containing the user's name.
type AdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionId   string `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ActionName string `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Fak        string `protobuf:"bytes,3,opt,name=fak,proto3" json:"fak,omitempty"`
}

func (x *AdminRequest) Reset() {
	*x = AdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRequest) ProtoMessage() {}

func (x *AdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRequest.ProtoReflect.Descriptor instead.
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{4}
}

func (x *AdminRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *AdminRequest) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *AdminRequest) GetFak() string {
	if x != nil {
		return x.Fak
	}
	return ""
}

// The response message containing the greetings
type AdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AdminReply) Reset() {
	*x = AdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminReply) ProtoMessage() {}

func (x *AdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminReply.ProtoReflect.Descriptor instead.
func (*AdminReply) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{5}
}

func (x *AdminReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

//structs for handling reception of newly generated shell schema on admin side
type NewShellSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type            string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` //not sure if what all params we need right now
	JsonShellSchema string `protobuf:"bytes,2,opt,name=jsonShellSchema,proto3" json:"jsonShellSchema,omitempty"`
}

func (x *NewShellSchema) Reset() {
	*x = NewShellSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewShellSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewShellSchema) ProtoMessage() {}

func (x *NewShellSchema) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewShellSchema.ProtoReflect.Descriptor instead.
func (*NewShellSchema) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{6}
}

func (x *NewShellSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NewShellSchema) GetJsonShellSchema() string {
	if x != nil {
		return x.JsonShellSchema
	}
	return ""
}

type NewShellSchemaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonFAK string `protobuf:"bytes,1,opt,name=jsonFAK,proto3" json:"jsonFAK,omitempty"`
}

func (x *NewShellSchemaResponse) Reset() {
	*x = NewShellSchemaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewShellSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewShellSchemaResponse) ProtoMessage() {}

func (x *NewShellSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewShellSchemaResponse.ProtoReflect.Descriptor instead.
func (*NewShellSchemaResponse) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{7}
}

func (x *NewShellSchemaResponse) GetJsonFAK() string {
	if x != nil {
		return x.JsonFAK
	}
	return ""
}

type ConsensusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity           string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Chunk              string `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	TimeInMilliseconds int32  `protobuf:"varint,3,opt,name=timeInMilliseconds,proto3" json:"timeInMilliseconds,omitempty"`
	Result             string `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Message            string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	NextAction         string `protobuf:"bytes,6,opt,name=nextAction,proto3" json:"nextAction,omitempty"`
}

func (x *ConsensusRequest) Reset() {
	*x = ConsensusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsensusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusRequest) ProtoMessage() {}

func (x *ConsensusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusRequest.ProtoReflect.Descriptor instead.
func (*ConsensusRequest) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{8}
}

func (x *ConsensusRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ConsensusRequest) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *ConsensusRequest) GetTimeInMilliseconds() int32 {
	if x != nil {
		return x.TimeInMilliseconds
	}
	return 0
}

func (x *ConsensusRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ConsensusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConsensusRequest) GetNextAction() string {
	if x != nil {
		return x.NextAction
	}
	return ""
}

type ActionDataRequest_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidatorID string `protobuf:"bytes,1,opt,name=ValidatorID,proto3" json:"ValidatorID,omitempty"`
	Result      bool   `protobuf:"varint,2,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *ActionDataRequest_Result) Reset() {
	*x = ActionDataRequest_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionDataRequest_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDataRequest_Result) ProtoMessage() {}

func (x *ActionDataRequest_Result) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDataRequest_Result.ProtoReflect.Descriptor instead.
func (*ActionDataRequest_Result) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ActionDataRequest_Result) GetValidatorID() string {
	if x != nil {
		return x.ValidatorID
	}
	return ""
}

func (x *ActionDataRequest_Result) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ActionDataRequest_Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionID   string `protobuf:"bytes,1,opt,name=ActionID,proto3" json:"ActionID,omitempty"`
	ActionType string `protobuf:"bytes,2,opt,name=ActionType,proto3" json:"ActionType,omitempty"`
	ActionData string `protobuf:"bytes,3,opt,name=ActionData,proto3" json:"ActionData,omitempty"`
	ResourceID string `protobuf:"bytes,4,opt,name=ResourceID,proto3" json:"ResourceID,omitempty"`
}

func (x *ActionDataRequest_Action) Reset() {
	*x = ActionDataRequest_Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionDataRequest_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDataRequest_Action) ProtoMessage() {}

func (x *ActionDataRequest_Action) ProtoReflect() protoreflect.Message {
	mi := &file_communication_grpc_schema_blockchain_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDataRequest_Action.ProtoReflect.Descriptor instead.
func (*ActionDataRequest_Action) Descriptor() ([]byte, []int) {
	return file_communication_grpc_schema_blockchain_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ActionDataRequest_Action) GetActionID() string {
	if x != nil {
		return x.ActionID
	}
	return ""
}

func (x *ActionDataRequest_Action) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionDataRequest_Action) GetActionData() string {
	if x != nil {
		return x.ActionData
	}
	return ""
}

func (x *ActionDataRequest_Action) GetResourceID() string {
	if x != nil {
		return x.ResourceID
	}
	return ""
}

var File_communication_grpc_schema_blockchain_proto protoreflect.FileDescriptor

var file_communication_grpc_schema_blockchain_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x72,
	0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x22, 0x25, 0x0a, 0x0f,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x22, 0x22, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x1c, 0x0a, 0x06, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x98, 0x03, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x46, 0x41, 0x4b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x46, 0x41, 0x4b, 0x12,
	0x42, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x12, 0x40, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x42, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x84, 0x01, 0x0a, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x44,
	0x22, 0x5e, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x66, 0x61, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x61, 0x6b,
	0x22, 0x26, 0x0a, 0x0a, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4e, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x53,
	0x68, 0x65, 0x6c, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x6a, 0x73, 0x6f, 0x6e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6a, 0x73, 0x6f, 0x6e, 0x53, 0x68, 0x65,
	0x6c, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x32, 0x0a, 0x16, 0x4e, 0x65, 0x77, 0x53,
	0x68, 0x65, 0x6c, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x73, 0x6f, 0x6e, 0x46, 0x41, 0x4b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x73, 0x6f, 0x6e, 0x46, 0x41, 0x4b, 0x22, 0xc6, 0x01, 0x0a,
	0x10, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x2e, 0x0a, 0x12, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d, 0x69, 0x6c,
	0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x12, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x95, 0x04, 0x0a, 0x15, 0x47, 0x72, 0x70, 0x63, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4d, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1c, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x51, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x14, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4e,
	0x65, 0x77, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1e, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x4e,
	0x65, 0x77, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a, 0x26, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x4e,
	0x65, 0x77, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x43,
	0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x12, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e,
	0x73, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a,
	0x10, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_communication_grpc_schema_blockchain_proto_rawDescOnce sync.Once
	file_communication_grpc_schema_blockchain_proto_rawDescData = file_communication_grpc_schema_blockchain_proto_rawDesc
)

func file_communication_grpc_schema_blockchain_proto_rawDescGZIP() []byte {
	file_communication_grpc_schema_blockchain_proto_rawDescOnce.Do(func() {
		file_communication_grpc_schema_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(file_communication_grpc_schema_blockchain_proto_rawDescData)
	})
	return file_communication_grpc_schema_blockchain_proto_rawDescData
}

var file_communication_grpc_schema_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_communication_grpc_schema_blockchain_proto_goTypes = []interface{}{
	(*SuccessResponse)(nil),          // 0: grpcBlockchain.SuccessResponse
	(*EmptyRequest)(nil),             // 1: grpcBlockchain.EmptyRequest
	(*Wallet)(nil),                   // 2: grpcBlockchain.Wallet
	(*ActionDataRequest)(nil),        // 3: grpcBlockchain.ActionDataRequest
	(*AdminRequest)(nil),             // 4: grpcBlockchain.AdminRequest
	(*AdminReply)(nil),               // 5: grpcBlockchain.AdminReply
	(*NewShellSchema)(nil),           // 6: grpcBlockchain.NewShellSchema
	(*NewShellSchemaResponse)(nil),   // 7: grpcBlockchain.NewShellSchemaResponse
	(*ConsensusRequest)(nil),         // 8: grpcBlockchain.ConsensusRequest
	(*ActionDataRequest_Result)(nil), // 9: grpcBlockchain.ActionDataRequest.Result
	(*ActionDataRequest_Action)(nil), // 10: grpcBlockchain.ActionDataRequest.Action
}
var file_communication_grpc_schema_blockchain_proto_depIdxs = []int32{
	9,  // 0: grpcBlockchain.ActionDataRequest.Results:type_name -> grpcBlockchain.ActionDataRequest.Result
	10, // 1: grpcBlockchain.ActionDataRequest.action:type_name -> grpcBlockchain.ActionDataRequest.Action
	1,  // 2: grpcBlockchain.GrpcBlockchainService.PrintChain:input_type -> grpcBlockchain.EmptyRequest
	2,  // 3: grpcBlockchain.GrpcBlockchainService.CreateChain:input_type -> grpcBlockchain.Wallet
	3,  // 4: grpcBlockchain.GrpcBlockchainService.CreateActionData:input_type -> grpcBlockchain.ActionDataRequest
	4,  // 5: grpcBlockchain.GrpcBlockchainService.ProcessAdminRequest:input_type -> grpcBlockchain.AdminRequest
	6,  // 6: grpcBlockchain.GrpcBlockchainService.HandleNewShellSchema:input_type -> grpcBlockchain.NewShellSchema
	8,  // 7: grpcBlockchain.GrpcBlockchainService.SendConsensus:input_type -> grpcBlockchain.ConsensusRequest
	0,  // 8: grpcBlockchain.GrpcBlockchainService.PrintChain:output_type -> grpcBlockchain.SuccessResponse
	0,  // 9: grpcBlockchain.GrpcBlockchainService.CreateChain:output_type -> grpcBlockchain.SuccessResponse
	0,  // 10: grpcBlockchain.GrpcBlockchainService.CreateActionData:output_type -> grpcBlockchain.SuccessResponse
	5,  // 11: grpcBlockchain.GrpcBlockchainService.ProcessAdminRequest:output_type -> grpcBlockchain.AdminReply
	7,  // 12: grpcBlockchain.GrpcBlockchainService.HandleNewShellSchema:output_type -> grpcBlockchain.NewShellSchemaResponse
	0,  // 13: grpcBlockchain.GrpcBlockchainService.SendConsensus:output_type -> grpcBlockchain.SuccessResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_communication_grpc_schema_blockchain_proto_init() }
func file_communication_grpc_schema_blockchain_proto_init() {
	if File_communication_grpc_schema_blockchain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_communication_grpc_schema_blockchain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_grpc_schema_blockchain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_grpc_schema_blockchain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_grpc_schema_blockchain_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_grpc_schema_blockchain_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_grpc_schema_blockchain_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_grpc_schema_blockchain_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewShellSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_grpc_schema_blockchain_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewShellSchemaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_grpc_schema_blockchain_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsensusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_grpc_schema_blockchain_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionDataRequest_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_grpc_schema_blockchain_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionDataRequest_Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_communication_grpc_schema_blockchain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communication_grpc_schema_blockchain_proto_goTypes,
		DependencyIndexes: file_communication_grpc_schema_blockchain_proto_depIdxs,
		MessageInfos:      file_communication_grpc_schema_blockchain_proto_msgTypes,
	}.Build()
	File_communication_grpc_schema_blockchain_proto = out.File
	file_communication_grpc_schema_blockchain_proto_rawDesc = nil
	file_communication_grpc_schema_blockchain_proto_goTypes = nil
	file_communication_grpc_schema_blockchain_proto_depIdxs = nil
}
